name: example-loadsample
on:
  push:
    paths-ignore:
    - 'docs/**'    
    - '**.md'
    - '.github/workflows/ubuntu_x64_cmake.yml'

  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: actions/checkout@v2
      with:
        repository: newdigate/teensy-cmake-macros
        path: deps/teensy-cmake-macros

    - uses: actions/checkout@v2
      with:
        repository: PaulStoffregen/cores.git
        path: deps/cores
        fetch-depth: 1
        ref: master

    - uses: actions/checkout@v2
      with:
        repository: PaulStoffregen/Audio.git
        path: deps/Audio
        fetch-depth: 1
        ref: master

    - uses: actions/checkout@v2
      with:
        repository: PaulStoffregen/SD.git
        path: deps/SD
        fetch-depth: 1
        ref: Juse_Use_SdFat

    - uses: actions/checkout@v2
      with:
        repository: PaulStoffregen/Wire.git
        path: deps/Wire
        fetch-depth: 1
        ref: master

    - uses: actions/checkout@v2
      with:
        repository: PaulStoffregen/SPI.git
        path: deps/SPI
        fetch-depth: 1
        ref: master

    - uses: actions/checkout@v2
      with:
        repository: PaulStoffregen/SerialFlash.git
        path: deps/SerialFlash
        fetch-depth: 1
        ref: master

    - uses: actions/checkout@v2
      with:
        repository: PaulStoffregen/arm_math.git
        path: deps/arm_math
        ref: master

    - uses: actions/checkout@v2
      with:
        repository: PaulStoffregen/SdFat.git
        path: deps/SdFat
        fetch-depth: 1
        ref: master

    - uses: actions/checkout@v2
      with:
        repository: PaulStoffregen/LittleFS.git
        path: deps/LittleFS
        fetch-depth: 1
        ref: main

    - uses: actions/checkout@v2
      with:
        repository: newdigate/teensy-variable-playback.git
        path: deps/teensy-variable-playback
        fetch-depth: 1
        ref: master

    - name: download toolchain
      run: |
        curl  -L "https://developer.arm.com/-/media/Files/downloads/gnu-rm/10.3-2021.10/gcc-arm-none-eabi-10.3-2021.10-x86_64-linux.tar.bz2?rev=78196d3461ba4c9089a67b5f33edf82a&hash=5631ACEF1F8F237389F14B41566964EC" --output /tmp/gcc-arm-none-eabi.tar.bz2
        mkdir -p /opt
        cd /opt
        tar xjf /tmp/gcc-arm-none-eabi.tar.bz2
        rm /tmp/gcc-arm-none-eabi.tar.bz2
        echo "/opt/gcc-arm-none-eabi-9-2019-q4-major/bin"

    - name: install teensy-cmake-macros
      run: cd deps/teensy-cmake-macros && mkdir cmake-build-debug && cd cmake-build-debug && cmake -DCMAKE_BUILD_TYPE=Debug .. && sudo make install

    - name: build
      run: mkdir cmake-build-debug && cd cmake-build-debug && cmake .. -DCMAKE_TOOLCHAIN_FILE:FILEPATH="${{github.workspace}}/cmake/toolchains/teensy41.cmake" && make loadsample_hex
